"""create roads table

Revision ID: b9132364c324
Revises: c66019113576
Create Date: 2026-09-19 13:39:48.861331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9132364c324'
down_revision = 'c66019113576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('highway_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roads_id'), 'roads', ['id'], unique=False)
    op.create_index(op.f('ix_roads_osm_id'), 'roads', ['osm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roads_osm_id'), table_name='roads')
    op.drop_index(op.f('ix_roads_id'), table_name='roads')
    op.drop_table('roads')
    # ### end Alembic commands ###
