"""add city relationship to tenants

Revision ID: c66019113576
Revises: f7dd01914560
Create Date: 2026-09-16 07:02:13.063729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66019113576'
down_revision = 'f7dd01914560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tenants_city_id'), 'tenants', ['city_id'], unique=False)
    op.create_foreign_key(None, 'tenants', 'cities', ['city_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_tenants_city_id'), table_name='tenants')
    op.drop_column('tenants', 'city_id')
    # ### end Alembic commands ###
